name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      fail-fast: true
      matrix:
        include:
          - php: '7.3'
            laravel: '5.8.*'
          - php: '7.3'
            laravel: '6.*'
          - php: '7.4'
            laravel: '7.*'
          - php: '7.4'
            laravel: '8.*'

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Require Laravel version
        run: composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Check coding standards
        run: vendor/bin/phpcs

      - name: Run tests
        run: vendor/bin/phpunit
